# Generated by Django 4.0.4 on 2022-06-12 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_follow_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='Followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
